Update deprecated-images.yml
MicrosoftDocs/azure-compute-docs pull request #58
Opened 2024-10-03 23:09 UTC by Olosinsk-commits

based on the workitem https://msazure.visualstudio.com/One/_workitems/edit/29745968

2024-10-03 23:16 UTC, Olosinsk-commits commented
#assign-reviewer: ebolton-cyber

2024-10-03 23:24 UTC, Olosinsk-commits commented
#sign-off (public repo)

2024-10-04 14:18 UTC, ShannonLeavitt commented
@ju-shim

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-10-04 17:16 UTC, ebolton-cyber approved these changes
Changes look good. This will optimize the cli commands/scripts for customers to find deprecated images more easily

2024-10-16 19:50 UTC, ebolton-cyber approved these changes

2024-10-23 23:08 UTC, ju-shim requested changes

2024-10-23 23:08 UTC, ju-shim commented on articles/virtual-machines/deprecated-images.yml
> +          - Run [Get-AzVMImageDeprecationStatus.ps1](https://github.com/Azure/azure-support-scripts/tree/master/VMImages#readme) to **list if any VMs or VMSS in a subscription were created from VM im
```suggestion
          - Run [Get-AzVMImageDeprecationStatus.ps1](https://github.com/Azure/azure-support-scripts/tree/master/VMImages#readme) to list if any VMs or VM scale sets in a subscription were created from VM images that are scheduled for deprecation.
```

2024-10-24 15:50 UTC, ju-shim approved these changes

2024-10-24 15:50 UTC, ju-shim commented
#sign-off

2024-10-24 16:00 UTC, merged